import { Creator, JobListing } from "@/lib/types";

export const mockCreators: Creator[] = [
  {
    id: "bxg-my-00001",
    credentialNumber: "BXG · MY · 00001",
    name: "Naomi Tan",
    handle: "@naomitan",
    slug: "naomi-tan",
    niche: "Beauty",
    location: "KL",
    followers: 120000,
    engagementRate: 5.2,
    platforms: ["Instagram", "TikTok"],
    baseRate: 1200,
    verified: true,
    foundingMember: true,
    bio: "Beauty creator and skincare enthusiast.",
    audience: "Urban women 21-34 in Malaysia.",
    contentDescription: "Ingredient-first skincare routines and GRWM videos.",
    brandsWorkedWith: ["Crocs", "G-Shock", "Rare Beauty", "Uniqlo", "GSC Movies"],
    audienceDemographics: { Chinese: 55, Malay: 25, Indian: 15, Japanese: 5 },
    languages: ["English", "Mandarin", "Bahasa Malaysia"],
  },
  {
    id: "bxg-my-00002",
    credentialNumber: "BXG · MY · 00002",
    name: "Aina Razak",
    handle: "@ainaeats",
    slug: "aina-razak",
    niche: "Food",
    location: "Penang",
    followers: 89000,
    engagementRate: 4.8,
    platforms: ["Instagram", "YouTube"],
    baseRate: 900,
    verified: true,
    foundingMember: false,
    bio: "Street food and premium dining storyteller.",
    audience: "Food-first Gen Z and millennials.",
    contentDescription: "Taste tests, location features, chef interviews.",
    brandsWorkedWith: ["GSC Movies", "Uniqlo"],
    audienceDemographics: { Chinese: 48, Malay: 31, Indian: 17, Japanese: 4 },
    languages: ["English", "Bahasa Malaysia"],
  },
  {
    id: "bxg-my-00003",
    credentialNumber: "BXG · MY · 00003",
    name: "Kai Lim",
    handle: "@kaifits",
    slug: "kai-lim",
    niche: "Fashion",
    location: "JB",
    followers: 153000,
    engagementRate: 6.1,
    platforms: ["Instagram", "TikTok"],
    baseRate: 1700,
    verified: true,
    foundingMember: true,
    bio: "Streetwear creator and stylist.",
    audience: "Male and female trend seekers 18-30.",
    contentDescription: "Lookbooks and styling tutorials.",
    brandsWorkedWith: ["Crocs", "Uniqlo"],
    audienceDemographics: { Chinese: 50, Malay: 30, Indian: 16, Japanese: 4 },
    languages: ["English", "Mandarin"],
  },
  {
    id: "bxg-my-00004",
    credentialNumber: "BXG · MY · 00004",
    name: "Yana Idris",
    handle: "@yanalife",
    slug: "yana-idris",
    niche: "Lifestyle",
    location: "KL",
    followers: 76000,
    engagementRate: 4.1,
    platforms: ["Instagram", "TikTok"],
    baseRate: 800,
    verified: false,
    foundingMember: false,
    bio: "Lifestyle and productivity creator.",
    audience: "Working professionals and students.",
    contentDescription: "Routines, organization, wellness habits.",
    brandsWorkedWith: ["G-Shock"],
    audienceDemographics: { Chinese: 45, Malay: 37, Indian: 14, Japanese: 4 },
    languages: ["English", "Bahasa Malaysia"],
  },
  {
    id: "bxg-my-00005",
    credentialNumber: "BXG · MY · 00005",
    name: "Ryan Chong",
    handle: "@ryantechmy",
    slug: "ryan-chong",
    niche: "Tech",
    location: "Cyberjaya",
    followers: 64000,
    engagementRate: 5.7,
    platforms: ["YouTube", "TikTok"],
    baseRate: 1100,
    verified: true,
    foundingMember: false,
    bio: "Consumer tech reviewer for SEA audiences.",
    audience: "Tech buyers and startup operators.",
    contentDescription: "Device reviews and app workflows.",
    brandsWorkedWith: ["G-Shock"],
    audienceDemographics: { Chinese: 52, Malay: 28, Indian: 16, Japanese: 4 },
    languages: ["English", "Mandarin"],
  },
  {
    id: "bxg-my-00006",
    credentialNumber: "BXG · MY · 00006",
    name: "Mira Sofea",
    handle: "@miratravels",
    slug: "mira-sofea",
    niche: "Travel",
    location: "Langkawi",
    followers: 98000,
    engagementRate: 5.0,
    platforms: ["Instagram", "YouTube"],
    baseRate: 1350,
    verified: false,
    foundingMember: false,
    bio: "Travel storyteller focused on hidden gems.",
    audience: "Family and couple trip planners.",
    contentDescription: "Local travel guides and itinerary reels.",
    brandsWorkedWith: ["GSC Movies"],
    audienceDemographics: { Chinese: 42, Malay: 40, Indian: 14, Japanese: 4 },
    languages: ["English", "Bahasa Malaysia"],
  },
];

export const mockJobs: JobListing[] = [
  {
    id: "job-001",
    brandName: "Luxe Skincare Co.",
    contactPerson: { name: "Marcus Thorne", title: "HR Executive", photoUrl: "" },
    description:
      "Looking for high production video creators for a 3 month campaign focusing on nighttime routines.",
    niche: "Beauty",
    format: "Long-Form",
    platform: "Instagram",
    rateRange: { min: 1500, max: 3000 },
    matchScore: 87,
    brandReviews: [
      {
        rating: 4.5,
        body: "Great communication and fast approvals. Payment landed on time.",
        campaignType: "Product Launch",
        date: "Feb 2025",
      },
      {
        rating: 4.1,
        body: "Clear brief, slight delay in final feedback cycle.",
        campaignType: "UGC Sprint",
        date: "Nov 2024",
      },
    ],
    communityThreads: [
      { title: "How strict is revision policy?", replies: 12 },
      { title: "Anyone done paid whitelisting with them?", replies: 7 },
    ],
  },
  {
    id: "job-002",
    brandName: "Urban Bite",
    contactPerson: { name: "Alyssa Teh", title: "Marketing Lead", photoUrl: "" },
    description:
      "Seeking food creators for weekly short-form launches tied to seasonal menus.",
    niche: "Food",
    format: "Short-Form",
    platform: "TikTok",
    rateRange: { min: 800, max: 1500 },
    matchScore: 76,
    brandReviews: [
      {
        rating: 3.9,
        body: "Good communication but approvals can be slow during campaign peaks.",
        campaignType: "Store Opening",
        date: "Jan 2025",
      },
    ],
    communityThreads: [{ title: "Best-performing deliverable format?", replies: 5 }],
  },
  {
    id: "job-003",
    brandName: "Threadline Studio",
    contactPerson: { name: "Irfan Malik", title: "Partnership Manager", photoUrl: "" },
    description:
      "Fashion lookbook campaign for Eid collections; request 2 reels and 8 story frames.",
    niche: "Fashion",
    format: "Hybrid",
    platform: "Instagram",
    rateRange: { min: 2000, max: 4200 },
    matchScore: 82,
    brandReviews: [
      {
        rating: 4.6,
        body: "Excellent creative freedom and fast payment cycle.",
        campaignType: "Seasonal Capsule",
        date: "Mar 2025",
      },
    ],
    communityThreads: [{ title: "Any exclusivity clauses in contracts?", replies: 9 }],
  },
];

export const analyticsData = {
  audience: [
    { name: "Chinese", value: 55 },
    { name: "Malay", value: 25 },
    { name: "Indian", value: 15 },
    { name: "Japanese", value: 5 },
  ],
  performanceHistory: [
    { year: "2021", engagement: 2.3, reach: 42 },
    { year: "2022", engagement: 3.1, reach: 58 },
    { year: "2023", engagement: 3.8, reach: 72 },
    { year: "2024", engagement: 4.6, reach: 86 },
    { year: "2025", engagement: 5.4, reach: 97 },
  ],
  seasonalEngagement: [
    { season: "Winter", instagram: 3.2, tiktok: 3.7, youtube: 2.1 },
    { season: "Spring", instagram: 4.2, tiktok: 4.8, youtube: 2.7 },
    { season: "Summer", instagram: 5.3, tiktok: 5.7, youtube: 3.5 },
    { season: "Fall", instagram: 4.5, tiktok: 5.1, youtube: 3.1 },
  ],
  platformGrowth: [
    { month: "Jan", instagram: 32, tiktok: 21, youtube: 12 },
    { month: "Feb", instagram: 38, tiktok: 24, youtube: 13 },
    { month: "Mar", instagram: 44, tiktok: 28, youtube: 16 },
    { month: "Apr", instagram: 50, tiktok: 33, youtube: 19 },
  ],
};
